Second tutorial material
scorelab/Codelabz pull request #150
Opened 2021-07-20 19:40 UTC by rijusougata13

## Description

TutorialPage sub components 
## Related Issue

Fixed #148 

## How Has This Been Tested?

with npm start
## Screenshots or GIF (In case of UI changes):
# Desktop View
![Screenshot from 2021-07-21 01-01-39](https://user-images.githubusercontent.com/52108435/126385301-a2647210-6574-480d-b582-a5a959ce2ae7.png)
# Mobile View
![Screenshot from 2021-07-21 01-02-14](https://user-images.githubusercontent.com/52108435/126385312-8e930a7d-18a1-41b2-941f-ff27e59a2c19.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-21 05:55 UTC, thisuraseniya commented on src/components/Tutorials/subComps/ColorPickerModal.js
> +      aria-describedby="simple-modal-description"
Let's update or remove these

2021-07-21 05:57 UTC, thisuraseniya requested changes

2021-07-21 05:57 UTC, thisuraseniya commented on src/components/Tutorials/subComps/ColorPickerModal.js
> +      aria-describedby="simple-modal-description"
These two can be updated / removed

2021-07-21 08:45 UTC, rijusougata13 commented on src/components/Tutorials/subComps/ColorPickerModal.js
> +      aria-describedby="simple-modal-description"
done!

2021-07-22 06:28 UTC, thisuraseniya approved these changes

2021-07-22 17:00 UTC, shehand approved these changes

2021-07-23 04:05 UTC, Niweera approved these changes

2021-07-23 08:47 UTC, merged