Cypress test for login, signup, forgotpassword
scorelab/Codelabz pull request #169
Opened 2021-08-02 10:43 UTC by rijusougata13

## Description

Cypress test for login, signup, forgotpassword
## Related Issue
Fixed #168 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-08-04 15:07 UTC, thisuraseniya approved these changes

2021-08-04 15:08 UTC, thisuraseniya requested changes
Please fix the merge conflicts

2021-08-04 19:25 UTC, rijusougata13 commented
> Please fix the merge conflicts

Fixed

2021-08-05 07:30 UTC, Niweera approved these changes

2021-08-05 15:48 UTC, shehand approved these changes

2021-08-06 14:00 UTC, merged