Add the feature for filtering posts through popular tags
scorelab/Codelabz pull request #210
Opened 2022-02-06 11:10 UTC by sakkshm26

## Description

Added the feature for filtering posts by clicking on popular tags.

## Related Issue

Fixes: #209.

## Motivation and Context

This change will allow the users to easily search for a post with a particular tag.

## Screenshots or GIF (In case of UI changes):

https://user-images.githubusercontent.com/87091886/152677939-28db052a-62db-4e73-80ad-740341e9c3e8.mp4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-20 16:40 UTC, sakkshm26 commented
@charithccmc @Niweera @shehand @Wathsara @rijusougata13  can you please review?

2022-02-23 14:25 UTC, shehand requested changes

2022-03-01 15:11 UTC, sakkshm26 commented on src/components/HomePage/index.js
>            <Grid container alignItems="left">
Alright, thank you for the review :)

2022-08-05 09:09 UTC, shahaab commented
@Niweera we can close this as well as shehand has already reviewed it.

2022-08-05 10:49 UTC, closed without merging