📄 added table of content inside README
scorelab/Codelabz pull request #418
Opened 2022-08-28 21:20 UTC by nitinmewar

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots or GIF (In case of UI changes):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-30 17:46 UTC, Sarfraz-droid requested changes

2022-08-30 17:46 UTC, Sarfraz-droid commented on README.md
> +- [CodeLabz](#codelabz)
Try adding like this instead

1. [CodeLabz](#codelabz)
2. [Deployed on](#deployed-on)
  1. [User Guide](#user-guide)
      1. [How to Setup](#how-to-setup)
      2. [How to Use](#how-to-use)
  2. [Set-up-Firebase](#set-up-firebase)
      1. [How to Deploy Firebase Cloud Functions](#how-to-deploy-firebase-cloud-functions)

2022-08-30 17:46 UTC, Sarfraz-droid commented on README.md
> +  * [**How to Configure**](#--how-to-configure--)
```
//Not working
  * [**How to install**](#--how-to-install--)
      - [Before installing the Emulator Suite you will need:-](#before-installing-the-emulator-suite-you-will-need--)
      - [To install the Emulator Suite:](#to-install-the-emulator-suite-)
  * [**How to Configure**](#--how-to-configure--)
      - [Configure Emulator Suite:-](#configure-emulator-suite--)
      - [Port Configuration - These are the Default Ports Provided you can change them while initializing(if needed)](#port-configuration---these-are-the-default-ports-provided-you-can-change-them-while-initializing-if-needed-)
      - [To Start the Emulators:-](#to-start-the-emulators--)
      - [Import and Export:-](#import-and-export--)
```

2022-08-31 09:03 UTC, Sarfraz-droid commented
@nitinmewar have a look on the requested changes above

2022-09-02 13:16 UTC, Sarfraz-droid approved these changes

2022-09-02 13:16 UTC, Sarfraz-droid commented
LGTM

2022-09-03 07:42 UTC, Maahi10001 approved these changes

2022-09-03 08:13 UTC, merged