Edit Organisation Button added
scorelab/Codelabz pull request #477
Opened 2022-10-16 19:04 UTC by ayush3160

## Description
Edit organisation button added onClicking it will redirect to /organization route.

## Related Issue

#474 

## Motivation and Context

## How Has This Been Tested?

## Screenshots or GIF (In case of UI changes):
![Screenshot 2022-10-16 235015](https://user-images.githubusercontent.com/89914602/196053046-2a0ab208-ac3a-4ecd-996d-32c28a359b27.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-16 19:49 UTC, Sarfraz-droid approved these changes

2022-10-17 18:40 UTC, Sarfraz-droid requested changes

2022-10-17 18:40 UTC, Sarfraz-droid commented on src/components/ProfileBanner/Organization/index.js
> +                <Link
also add a check.
**Only and only if the organisation belongs to the user, then show this button**

2022-10-21 20:54 UTC, Niweera submitted a review, later dismissed

2022-10-22 05:20 UTC, Sarfraz-droid commented on src/components/ProfileBanner/Organization/index.js
> +                <Link
@ayush3160 please have a look at this

2022-10-31 17:34 UTC, Niweera commented
@ayush3160 is this pr finalized?

2022-11-01 11:15 UTC, Sarfraz-droid commented
@Niweera there are some changes that are required
- Currently the Edit Organization button will show on non-admins as well as admins we have to add a condition where the user has access to the organization

2022-11-01 12:08 UTC, Niweera commented
> @Niweera there are some changes that are required
> 
> * Currently the Edit Organization button will show on non-admins as well as admins we have to add a condition where the user has access to the organization

@ayush3160 can you please address this issue?

2022-11-05 05:50 UTC, Maahi10001 approved these changes

2022-12-06 09:01 UTC, Sarfraz-droid commented
Closing this PR due to inactivity

2022-12-06 09:01 UTC, closed without merging