UI/UX Improvement of Signup/login Page
scorelab/Codelabz pull request #515
Opened 2022-12-05 16:36 UTC by hs05june

#514

2022-12-05 20:24 UTC, Sarfraz-droid commented
@hs05june can you place add a screenshot or gif of your changes?

2022-12-05 20:26 UTC, Sarfraz-droid requested changes

2022-12-05 20:26 UTC, Sarfraz-droid commented on .env.sample
> -
remove changes from this file

2022-12-05 20:26 UTC, Sarfraz-droid commented on firebase.json
> -
avoid any changes in the root files, (except when its the main issue)
So remove any changes in `firebase.json` , `.env.sample` or `package.json`

2022-12-05 20:26 UTC, Sarfraz-droid commented on src/config/index.js
remove changes in this config file as well, as this is not a part of the issue

2022-12-06 04:48 UTC, hs05june commented
> 

[Screencast from 05-12-22 09:45:04 PM IST.webm](https://user-images.githubusercontent.com/103871275/205818341-019e4ab6-5c30-4fed-bcac-5e5ce0cb87ce.webm)
Done the suggested changes

2022-12-06 06:15 UTC, Sarfraz-droid approved these changes

2022-12-06 06:16 UTC, Sarfraz-droid requested changes

2022-12-06 06:16 UTC, Sarfraz-droid commented on src/components/AuthPage/SignUp/index.js
> +            <Link to="/login"><span style={{color:'#03AAFA'}} onMouseEnter={(e)=>{handleMouseEnter(e)}} onMouseLeave={(e)=>{handleMouseLeave(e)}}>Log In</span></Link>
Format your changes by using some formatter like prettier

2022-12-06 09:10 UTC, Maahi10001 approved these changes

2022-12-06 10:14 UTC, merged