Connection Request Button
scorelab/Codelabz pull request #522
Opened 2022-12-06 13:38 UTC by hs05june

## Description

## Related Issue

#521 
## Motivation and Context

## How Has This Been Tested?

## Screenshots or GIF (In case of UI changes):

[Gif of change](https://user-images.githubusercontent.com/103871275/205926818-056ebe1e-5d18-458a-9511-9618ce0c91cb.webm)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-12-07 07:17 UTC, Sarfraz-droid requested changes

2022-12-07 07:17 UTC, Sarfraz-droid commented on src/components/CardTabs/Users/index.js
>                    <img src={AddUser} />
Add conditional in `<img />` tag itself.
Handle the state using `useState` hook.

Currently the handle click function is adding up extra unnecessary complexity.

2022-12-07 08:58 UTC, Sarfraz-droid commented on src/components/CardTabs/Users/index.js
>                    <img src={AddUser} />
create a state inside the <UserElement /> instead. inside the component

2022-12-07 09:01 UTC, Sarfraz-droid commented on src/components/CardTabs/Users/index.js
>                    <img src={AddUser} />
yes

2022-12-08 11:53 UTC, Sarfraz-droid approved these changes

2022-12-10 07:23 UTC, hs05june commented
@Maahi10001 @Niweera Kindly review this PR. and suggest I need to make

2022-12-10 13:56 UTC, Maahi10001 approved these changes

2022-12-10 13:56 UTC, merged