change functionality  of "Send me the Link " button
scorelab/Codelabz pull request #802
Opened 2023-05-24 12:43 UTC by kushalShukla-web

…ome specific keywords then the button is not going to be disabled

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots or GIF (In case of UI changes):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-24 12:49 UTC, kushalShukla-web commented
@Niweera  pls review this pull request once

2023-05-24 12:55 UTC, kushalShukla-web commented
this pr closes the issue #803

2023-05-25 19:19 UTC, nikhilagastya commented
Is the issue still open ?

2023-06-16 11:03 UTC, Deeppjp116 requested changes

2023-06-16 11:03 UTC, Deeppjp116 commented on src/components/AuthPage/ForgotPassword/index.js
> +    if(email.includes('@gmail.com') && /[0-9]/.test(email) && /\p{L}/u.test(email)){
HI @kushalShukla-web  you can use this for validation 
/^[a-zA-Z0-9._%+-]+@gmail\.com$/

2023-07-12 15:08 UTC, closed without merging