ADD Notification Page Automatic issue labelers
scorelab/Codelabz pull request #804
Opened 2023-05-30 12:37 UTC by ABHISHEK-PANDEY2

Add Notification Page and automatic issue labeler 
## Description

A new page for notifications are added
## Related Issue

#809 
## Motivation and Context

## How Has This Been Tested?

## Screenshots or GIF (In case of UI changes):
![image](https://github.com/scorelab/Codelabz/assets/95560057/99db9b4d-c7e2-4aff-a667-cb8398625243)

![image](https://github.com/scorelab/Codelabz/assets/95560057/cde1ce59-9139-4ff3-8203-e6f8ce5f1618)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-23 15:09 UTC, Sarfraz-droid approved these changes

2023-06-23 15:14 UTC, Sarfraz-droid requested changes

2023-06-23 15:14 UTC, Sarfraz-droid commented on .github/labels.yml
> +borken:
typo . change it to `broken`

2023-06-24 15:30 UTC, ABHISHEK-PANDEY2 commented on .github/labels.yml
> +borken:
ok

2023-06-24 20:23 UTC, Sarfraz-droid submitted a review, later dismissed

2023-06-24 20:25 UTC, Maahi10001 approved these changes

2023-06-24 21:02 UTC, samyakshah3008 reviewed
Solid work @ABHISHEK-PANDEY2 💪 
However, I have added a few comments, please check and let me know your inputs on those comments😄
Cheers!

2023-06-24 21:02 UTC, samyakshah3008 commented on src/components/Notification/styles.jsx
> +    // direction: "column"
Same as above comment

2023-06-24 21:21 UTC, Sarfraz-droid commented on src/components/Notification/index.jsx
> +    }
@samyakshah3008 its just for testing right now. Will be updated once the backend is in development

2023-06-24 21:24 UTC, samyakshah3008 commented on src/components/Notification/index.jsx
> +    }
Sounds cool, thanks for clearing @Sarfraz-droid 😄

2023-06-24 21:26 UTC, Sarfraz-droid commented on src/components/Notification/NotificationBox.jsx
> +        style={{ backgroundColor: notification.isRead ? "#fff" : "#D9F1FC" }}
@ABHISHEK-PANDEY2 can be used instead `@mui/material/colors`

2023-06-24 21:35 UTC, Sarfraz-droid commented
Hi @samyakshah3008, Thank you for your input! Please note currently this is a dev PR in GSOC 23. So some of the code does include dummy data. But thankyou for your suggestions. I'll request the changes for the same.

2023-06-24 22:03 UTC, Sarfraz-droid approved these changes

2023-06-25 05:50 UTC, samyakshah3008 commented
> Hi @samyakshah3008, Thank you for your input! Please note currently this is a dev PR in GSOC 23. So some of the code does include dummy data. This will be updated and fixed in the next PRs.
> 
> But thankyou for your suggestions. I'll update the changes for the same.

Pleasure @Sarfraz-droid 😄 ✨  
Sure, I'll make sure about that dummy data point in next PR reviews! 

Cheers.

2023-06-25 10:10 UTC, shivareddy6 approved these changes

2023-06-25 14:18 UTC, merged