solve button send me the link is not up to date
scorelab/Codelabz pull request #808
Opened 2023-06-18 08:58 UTC by Deeppjp116

## Description
This pull request adds email validation and disables the button unless the email contains characters, numbers, and ends with "@gmail.com".

## Changes Made
- Updated the regular expression to match email addresses containing "@gmail.com".
- Updated the button disabling logic based on the email format.
- Added email input field and form submission functionality.

## Testing
- Tested the email validation with various scenarios, including valid and invalid email formats.
- Tested the button disabling behavior based on the email format.
- Verified that the form submission works as expected.

## Screenshots (if applicable)
https://youtu.be/AyH_u8X7p9s

## Checklist
- [ ] Code compiles correctly
- [ ] Tests passed successfully
- [ ] Verified that the changes work as expected

Please review the changes and let me know if any further modifications or tests are required. Thank you!

2023-06-23 15:18 UTC, Sarfraz-droid commented
Hi, @Deeppjp116 , Some tests are failing. can you update the empty email test or update it accordingly???

2023-06-23 15:19 UTC, Sarfraz-droid requested changes

2023-06-23 15:19 UTC, Sarfraz-droid commented on .env.sample
Don't delete the `.env.sample`. remove this change from your PR

2023-06-24 21:14 UTC, samyakshah3008 approved these changes
Solid work @Deeppjp116 💪 

I have added a few comments, please check! 
Rest looks good to me! 🚀

2023-06-24 21:14 UTC, samyakshah3008 commented on old_local-firebase-emulators-import-export.md
> +
Not sure the reason behind this empty line? can you please look into it?

2023-06-24 21:14 UTC, samyakshah3008 commented on src/components/AuthPage/ForgotPassword/index.jsx
> +  confirmationText = "We have sent you an email containing the link to reset your password .Please check your inbox including spams",
Nitpik: 
Can we modify your text as below:
"We have sent you an email containing the link to reset your password. Please check your inbox including spams"

Change: 
Add full stop after password and one gap after full stop

2023-06-24 21:14 UTC, samyakshah3008 commented on src/components/AuthPage/ForgotPassword/index.jsx
> +  const [open, setOpen] = React.useState(true);
Can we use `useState` as similar to what we did for above other useStates? This is creating code inconsistency I feel, what's your input?

2023-06-24 21:14 UTC, samyakshah3008 commented on src/components/AuthPage/ForgotPassword/index.jsx
> +          disabled={isButtonDisabled} // Disable the button if email format is incorrect
Great to see you have added comments, this is improving code quality!

2023-06-24 21:14 UTC, samyakshah3008 commented on src/components/AuthPage/ForgotPassword/index.jsx
> +          New to <span className="brand-font text-bold">CodeLabz</span>?{" "}
Can we please remove `{" "}` ?

2023-06-24 21:16 UTC, samyakshah3008 reviewed
Please address to @Sarfraz-droid requested changes.

2023-06-24 21:52 UTC, Sarfraz-droid commented
@Deeppjp116 I'm closing this PR for now. How about if you can create a new issue for the same and  discuss in the gitter channel [here](https://matrix.to/#/#scorelab_CodeLabz:gitter.im)?

2023-06-24 21:53 UTC, closed without merging

2023-06-27 05:19 UTC, Deeppjp116 commented on .env.sample
I apologise for the inconvenience, however I changed the file's name to ```.env```. I'll give an update soon.