Add Tutorial Page
scorelab/Codelabz pull request #821
Opened 2023-07-05 20:28 UTC by ABHISHEK-PANDEY2

## Description

Created a new component for tutorial pages, added reducers and actions for the same
## Related Issue

#820 
## Motivation and Context

There is currently no page to view tutorials
## How Has This Been Tested?

## Screenshots or GIF (In case of UI changes):

![image](https://github.com/scorelab/Codelabz/assets/95560057/7b449690-505f-4b0b-948e-0c71300d7ba8)

![image](https://github.com/scorelab/Codelabz/assets/95560057/f3263128-409a-4ebd-a473-2dedc7f471e5)

![8fDv1HfNsj](https://github.com/scorelab/Codelabz/assets/95560057/2b2b5f6e-eeb4-469f-acf8-c2b79ed4d2f3)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-07-07 16:43 UTC, Sarfraz-droid requested changes

2023-07-07 16:43 UTC, Sarfraz-droid commented on src/components/TutorialPage/components/PostDetails.jsx
> +              {/* </Grid> */}
remove this comment

2023-07-08 06:39 UTC, ABHISHEK-PANDEY2 commented on src/components/TutorialPage/StepList.jsx
> +                    <ListItemText
Its clickable

2023-07-08 07:27 UTC, Sarfraz-droid approved these changes

2023-07-08 14:31 UTC, Maahi10001 approved these changes

2023-07-08 21:01 UTC, merged